/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module game_12 (
    input clk,
    input rst,
    input io_button_left,
    input io_button_right,
    input io_button_centre,
    input io_button_up,
    input io_button_down,
    output reg [15:0] player_position_out
  );
  
  
  
  wire [16-1:0] M_regfile_player_position_out;
  reg [16-1:0] M_regfile_player_position_in;
  regfile_18 regfile (
    .clk(clk),
    .rst(rst),
    .player_position_in(M_regfile_player_position_in),
    .player_position_out(M_regfile_player_position_out)
  );
  
  always @* begin
    M_regfile_player_position_in = M_regfile_player_position_out;
    player_position_out = M_regfile_player_position_out;
    if (io_button_centre == 1'h1) begin
      M_regfile_player_position_in = 16'h0000;
    end
    if (io_button_left == 1'h1) begin
      M_regfile_player_position_in[8+7-:8] = M_regfile_player_position_out[8+7-:8] - 1'h1;
    end
    if (io_button_right == 1'h1) begin
      M_regfile_player_position_in[8+7-:8] = M_regfile_player_position_out[8+7-:8] + 1'h1;
    end
    if (io_button_up == 1'h1) begin
      M_regfile_player_position_in[8+7-:8] = M_regfile_player_position_out[8+7-:8] - 5'h10;
    end
    if (io_button_down == 1'h1) begin
      M_regfile_player_position_in[8+7-:8] = M_regfile_player_position_out[8+7-:8] + 5'h10;
    end
  end
endmodule
