/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module map_41 (
    input clk,
    input rst,
    input button_reset,
    input button_stage_left,
    input button_stage_right,
    input win_bool_in,
    input loss_bool_in,
    output reg [255:0] map_out,
    output reg [15:0] player_position_out,
    output reg [7:0] win_position_out,
    output reg [1:0] map_index
  );
  
  
  
  localparam MAP1_map_fsm = 2'd0;
  localparam MAP2_map_fsm = 2'd1;
  localparam MAP3_map_fsm = 2'd2;
  
  reg [1:0] M_map_fsm_d, M_map_fsm_q = MAP1_map_fsm;
  
  always @* begin
    M_map_fsm_d = M_map_fsm_q;
    
    map_out = 1'h0;
    player_position_out = 1'h0;
    win_position_out = 1'h0;
    map_index = 1'h0;
    if (button_reset) begin
      M_map_fsm_d = MAP1_map_fsm;
    end
    if (win_bool_in || button_stage_right) begin
      M_map_fsm_d = MAP2_map_fsm;
    end
    
    case (M_map_fsm_q)
      MAP1_map_fsm: begin
        map_out = 256'h000000000000000000001c001f801ff00ff800f8007000000000000000000000;
        player_position_out = 16'h6400;
        win_position_out = 8'h9a;
        map_index = 1'h1;
        if (win_bool_in || button_stage_right) begin
          M_map_fsm_d = MAP2_map_fsm;
        end else begin
          if (loss_bool_in) begin
            M_map_fsm_d = MAP1_map_fsm;
          end
        end
      end
      MAP2_map_fsm: begin
        map_out = 256'h00000000000007f004f004fc7c0f0e0f0e07026003e003e001c0000000000000;
        player_position_out = 16'h6100;
        win_position_out = 7'h7e;
        map_index = 2'h2;
        if (win_bool_in || button_stage_right) begin
          M_map_fsm_d = MAP1_map_fsm;
        end else begin
          if (loss_bool_in || button_stage_left) begin
            M_map_fsm_d = MAP3_map_fsm;
          end
        end
      end
      MAP2_map_fsm: begin
        map_out = 256'h0000000000000000000003f8f398ff9ef01ef01e000e00000000000000000000;
        player_position_out = 16'h8100;
        win_position_out = 8'h8d;
        map_index = 2'h3;
        if (win_bool_in || button_stage_right) begin
          M_map_fsm_d = MAP1_map_fsm;
        end else begin
          if (loss_bool_in || button_stage_left) begin
            M_map_fsm_d = MAP2_map_fsm;
          end
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_map_fsm_q <= 1'h0;
    end else begin
      M_map_fsm_q <= M_map_fsm_d;
    end
  end
  
endmodule
