/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module rom_test_8 (
    input [3:0] address,
    output reg [7:0] letter
  );
  
  
  
  localparam TEXT = 88'h48656c6c6f576f726c6421;
  
  always @* begin
    letter = TEXT[(address)*8+7-:8];
  end
endmodule
