/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module eight_tester_2 (
    input clk,
    input rst,
    output reg a,
    output reg b,
    output reg cin,
    input s,
    input carry,
    input mode_dip,
    input [4:0] io_button,
    output reg [7:0] led_expected,
    output reg [7:0] led_result,
    output reg [7:0] led_test
  );
  
  
  
  reg [26:0] M_counter_d, M_counter_q = 1'h0;
  localparam ONE_state = 4'd0;
  localparam TWO_state = 4'd1;
  localparam THREE_state = 4'd2;
  localparam FOUR_state = 4'd3;
  localparam FIVE_state = 4'd4;
  localparam SIX_state = 4'd5;
  localparam SEVEN_state = 4'd6;
  localparam EIGHT_state = 4'd7;
  localparam PASS_state = 4'd8;
  
  reg [3:0] M_state_d, M_state_q = ONE_state;
  localparam AUTO_mode = 1'd0;
  localparam MANUAL_mode = 1'd1;
  
  reg M_mode_d, M_mode_q = AUTO_mode;
  
  always @* begin
    M_state_d = M_state_q;
    M_mode_d = M_mode_q;
    M_counter_d = M_counter_q;
    
    M_counter_d = M_counter_q + 1'h1;
    led_test = 1'h0;
    led_result = 1'h0;
    led_expected = 1'h0;
    led_test = 1'h0;
    a = 1'h0;
    b = 1'h0;
    cin = 1'h0;
    
    case (mode_dip)
      1'h0: begin
        M_mode_d = AUTO_mode;
      end
      1'h1: begin
        M_mode_d = MANUAL_mode;
      end
    endcase
    
    case (M_mode_q)
      AUTO_mode: begin
        
        case (M_state_q)
          ONE_state: begin
            led_expected = 8'h00;
            led_test = 8'h80;
            a = 1'h0;
            b = 1'h0;
            cin = 1'h0;
            if (s == 1'h0 && carry == 1'h0) begin
              led_result = 8'h80;
              if (M_counter_q[26+0-:1] == 1'h1) begin
                M_state_d = TWO_state;
              end
            end
          end
          TWO_state: begin
            led_expected = 8'h30;
            led_test = 8'h40;
            a = 1'h0;
            b = 1'h0;
            cin = 1'h1;
            if (s == 1'h1 && carry == 1'h0) begin
              led_result = 8'h40;
              if (M_counter_q[26+0-:1] == 1'h1) begin
                M_state_d = THREE_state;
              end
            end
          end
          THREE_state: begin
            led_expected = 8'h50;
            led_test = 8'h20;
            a = 1'h0;
            b = 1'h0;
            cin = 1'h1;
            if (s == 1'h1 && carry == 1'h0) begin
              led_result = 8'h20;
              if (M_counter_q[26+0-:1] == 1'h1) begin
                M_state_d = FOUR_state;
              end
            end
          end
          FOUR_state: begin
            led_expected = 8'h68;
            led_test = 8'h10;
            a = 1'h0;
            b = 1'h0;
            cin = 1'h1;
            if (s == 1'h0 && carry == 1'h1) begin
              led_result = 8'h10;
              if (M_counter_q[26+0-:1] == 1'h1) begin
                M_state_d = FIVE_state;
              end
            end
          end
          FIVE_state: begin
            led_expected = 8'h90;
            led_test = 8'h08;
            a = 1'h0;
            b = 1'h0;
            cin = 1'h1;
            if (s == 1'h1 && carry == 1'h0) begin
              led_result = 8'h08;
              if (M_counter_q[26+0-:1] == 1'h1) begin
                M_state_d = SIX_state;
              end
            end
          end
          SIX_state: begin
            led_expected = 8'ha8;
            led_test = 8'h04;
            a = 1'h0;
            b = 1'h0;
            cin = 1'h1;
            if (s == 1'h0 && carry == 1'h1) begin
              led_result = 8'h04;
              if (M_counter_q[26+0-:1] == 1'h1) begin
                M_state_d = SEVEN_state;
              end
            end
          end
          SEVEN_state: begin
            led_expected = 8'hc8;
            led_test = 8'h02;
            a = 1'h0;
            b = 1'h0;
            cin = 1'h1;
            if (s == 1'h0 && carry == 1'h1) begin
              led_result = 8'h02;
              if (M_counter_q[26+0-:1] == 1'h1) begin
                M_state_d = EIGHT_state;
              end
            end
          end
          EIGHT_state: begin
            led_expected = 8'hf8;
            led_test = 8'h01;
            a = 1'h0;
            b = 1'h0;
            cin = 1'h1;
            if (s == 1'h1 && carry == 1'h1) begin
              led_result = 8'h01;
              if (M_counter_q[26+0-:1] == 1'h1) begin
                M_state_d = PASS_state;
              end
            end
          end
          PASS_state: begin
            led_expected = 8'hff;
            led_test = 8'hff;
            led_result = 8'hff;
          end
        endcase
      end
      MANUAL_mode: begin
        
        case (M_state_q)
          ONE_state: begin
            led_expected = 8'h00;
            led_test = 8'h80;
            a = 1'h0;
            b = 1'h0;
            cin = 1'h0;
            if (s == 1'h0 && carry == 1'h0) begin
              led_result = 8'h80;
              if (M_counter_q[26+0-:1] == 1'h1) begin
                if (io_button[4+0-:1] == 1'h1) begin
                  M_state_d = TWO_state;
                end else begin
                  if (io_button[3+0-:1] == 1'h1) begin
                    M_state_d = EIGHT_state;
                  end else begin
                    if (io_button[1+0-:1] == 1'h1) begin
                      M_state_d = ONE_state;
                    end
                  end
                end
              end
            end
          end
          TWO_state: begin
            led_expected = 8'h30;
            led_test = 8'h40;
            a = 1'h0;
            b = 1'h0;
            cin = 1'h1;
            if (s == 1'h1 && carry == 1'h0) begin
              led_result = 8'h40;
              if (M_counter_q[26+0-:1] == 1'h1) begin
                if (io_button[4+0-:1] == 1'h1) begin
                  M_state_d = THREE_state;
                end else begin
                  if (io_button[3+0-:1] == 1'h1) begin
                    M_state_d = TWO_state;
                  end else begin
                    if (io_button[1+0-:1] == 1'h1) begin
                      M_state_d = ONE_state;
                    end
                  end
                end
              end
            end
          end
          THREE_state: begin
            led_expected = 8'h50;
            led_test = 8'h20;
            a = 1'h0;
            b = 1'h0;
            cin = 1'h1;
            if (s == 1'h1 && carry == 1'h0) begin
              led_result = 8'h20;
              if (M_counter_q[26+0-:1] == 1'h1) begin
                if (io_button[4+0-:1] == 1'h1) begin
                  M_state_d = FOUR_state;
                end else begin
                  if (io_button[3+0-:1] == 1'h1) begin
                    M_state_d = THREE_state;
                  end else begin
                    if (io_button[1+0-:1] == 1'h1) begin
                      M_state_d = ONE_state;
                    end
                  end
                end
              end
            end
          end
          FOUR_state: begin
            led_expected = 8'h68;
            led_test = 8'h10;
            a = 1'h0;
            b = 1'h0;
            cin = 1'h1;
            if (s == 1'h0 && carry == 1'h1) begin
              led_result = 8'h10;
              if (M_counter_q[26+0-:1] == 1'h1) begin
                if (io_button[4+0-:1] == 1'h1) begin
                  M_state_d = FIVE_state;
                end else begin
                  if (io_button[3+0-:1] == 1'h1) begin
                    M_state_d = THREE_state;
                  end else begin
                    if (io_button[1+0-:1] == 1'h1) begin
                      M_state_d = ONE_state;
                    end
                  end
                end
              end
            end
          end
          FIVE_state: begin
            led_expected = 8'h90;
            led_test = 8'h08;
            a = 1'h0;
            b = 1'h0;
            cin = 1'h1;
            if (s == 1'h1 && carry == 1'h0) begin
              led_result = 8'h08;
              if (M_counter_q[26+0-:1] == 1'h1) begin
                if (io_button[4+0-:1] == 1'h1) begin
                  M_state_d = SIX_state;
                end else begin
                  if (io_button[3+0-:1] == 1'h1) begin
                    M_state_d = FOUR_state;
                  end else begin
                    if (io_button[1+0-:1] == 1'h1) begin
                      M_state_d = ONE_state;
                    end
                  end
                end
              end
            end
          end
          SIX_state: begin
            led_expected = 8'ha8;
            led_test = 8'h04;
            a = 1'h0;
            b = 1'h0;
            cin = 1'h1;
            if (s == 1'h0 && carry == 1'h1) begin
              led_result = 8'h04;
              if (M_counter_q[26+0-:1] == 1'h1) begin
                if (io_button[4+0-:1] == 1'h1) begin
                  M_state_d = SEVEN_state;
                end else begin
                  if (io_button[3+0-:1] == 1'h1) begin
                    M_state_d = FIVE_state;
                  end else begin
                    if (io_button[1+0-:1] == 1'h1) begin
                      M_state_d = ONE_state;
                    end
                  end
                end
              end
            end
          end
          SEVEN_state: begin
            led_expected = 8'hc8;
            led_test = 8'h02;
            a = 1'h0;
            b = 1'h0;
            cin = 1'h1;
            if (s == 1'h0 && carry == 1'h1) begin
              led_result = 8'h02;
              if (M_counter_q[26+0-:1] == 1'h1) begin
                if (io_button[4+0-:1] == 1'h1) begin
                  M_state_d = EIGHT_state;
                end else begin
                  if (io_button[3+0-:1] == 1'h1) begin
                    M_state_d = SIX_state;
                  end else begin
                    if (io_button[1+0-:1] == 1'h1) begin
                      M_state_d = ONE_state;
                    end
                  end
                end
              end
            end
          end
          EIGHT_state: begin
            led_expected = 8'hf8;
            led_test = 8'h01;
            a = 1'h0;
            b = 1'h0;
            cin = 1'h1;
            if (s == 1'h1 && carry == 1'h1) begin
              led_result = 8'h01;
              if (M_counter_q[26+0-:1] == 1'h1) begin
                if (io_button[4+0-:1] == 1'h1) begin
                  M_state_d = ONE_state;
                end else begin
                  if (io_button[3+0-:1] == 1'h1) begin
                    M_state_d = SEVEN_state;
                  end else begin
                    if (io_button[1+0-:1] == 1'h1) begin
                      M_state_d = ONE_state;
                    end
                  end
                end
              end
            end
          end
        endcase
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
      M_state_q <= 1'h0;
      M_mode_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
      M_state_q <= M_state_d;
      M_mode_q <= M_mode_d;
    end
  end
  
endmodule
