/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module sixteenbitadder_4 (
    input [1:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg z,
    output reg v,
    output reg n,
    output reg [15:0] outputsum
  );
  
  
  
  reg [15:0] xordb;
  
  reg [16:0] sum;
  
  always @* begin
    xordb = b ^ {5'h10{alufn[0+0-:1]}};
    
    case (alufn[0+1-:2])
      2'h0: begin
        sum = a + b;
      end
      2'h1: begin
        sum = a - b;
      end
      default: begin
        sum = a + b;
      end
    endcase
    outputsum = sum[0+15-:16];
    z = 1'h0;
    if (sum == 16'h0000) begin
      z = 1'h1;
    end
    n = sum[15+0-:1];
    v = 1'h0;
    if (sum[16+0-:1] == 1'h1) begin
      v = 1'h1;
    end
  end
endmodule
