/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module bitshift_7 (
    input [15:0] inpa,
    input [15:0] inpb,
    input [5:0] alufn,
    output reg [15:0] shift
  );
  
  
  
  always @* begin
    
    case (alufn[0+1-:2])
      2'h0: begin
        shift = inpa << inpb[0+3-:4];
      end
      2'h1: begin
        shift = inpa >> inpb[0+3-:4];
      end
      2'h3: begin
        shift = inpa >>> inpb[0+3-:4];
      end
      default: begin
        shift = inpa;
      end
    endcase
  end
endmodule
