/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_bool_5 (
    input [15:0] a,
    input [15:0] b,
    input [3:0] aLUFN,
    output reg [15:0] bool
  );
  
  
  
  always @* begin
    
    case (aLUFN[0+3-:4])
      4'h8: begin
        bool = a & b;
      end
      4'he: begin
        bool = a | b;
      end
      4'h6: begin
        bool = a ^ b;
      end
      4'ha: begin
        bool = b;
      end
      4'hc: begin
        bool = a;
      end
      default: begin
        bool = 1'h0;
      end
    endcase
  end
endmodule
