/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module eight_fsm_2 (
    input clk,
    input rst,
    input [4:0] io_button,
    output reg [7:0] led
  );
  
  
  
  reg [26:0] M_counter_d, M_counter_q = 1'h0;
  localparam ONE_state = 2'd0;
  localparam TWO_state = 2'd1;
  localparam THREE_state = 2'd2;
  
  reg [1:0] M_state_d, M_state_q = ONE_state;
  
  always @* begin
    M_state_d = M_state_q;
    M_counter_d = M_counter_q;
    
    M_counter_d = M_counter_q + 1'h1;
    led = 1'h0;
    
    case (M_state_q)
      ONE_state: begin
        led = 8'h01;
        if (io_button[2+0-:1] == 1'h1) begin
          M_state_d = TWO_state;
        end else begin
          if (io_button[0+0-:1] == 1'h1) begin
            M_state_d = THREE_state;
          end
        end
      end
      TWO_state: begin
        led = 8'h02;
        if (io_button[2+0-:1] == 1'h1) begin
          M_state_d = THREE_state;
        end else begin
          if (io_button[0+0-:1] == 1'h1) begin
            M_state_d = ONE_state;
          end
        end
      end
      THREE_state: begin
        led = 8'h04;
        if (io_button[2+0-:1] == 1'h1) begin
          M_state_d = ONE_state;
        end else begin
          if (io_button[0+0-:1] == 1'h1) begin
            M_state_d = TWO_state;
          end
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
      M_state_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
      M_state_q <= M_state_d;
    end
  end
  
endmodule
